# Generated by Django 5.2.11 on 2026-03-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='parameter_type',
            field=models.CharField(choices=[('glucose', 'Glucosa'), ('spo2', 'SpO2'), ('pulse_rate', 'Frecuencia de pulso'), ('pi_index', 'Índice de perfusión'), ('hrv', 'Variabilidad de frecuencia cardíaca'), ('bp_systolic', 'Presión sistólica'), ('bp_diastolic', 'Presión diastólica'), ('temp', 'Temperatura'), ('otro', 'Otro')], max_length=50),
        ),
    ]
