# Generated by Django 5.2.11 on 2026-03-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('glucometro', 'Glucómetro'), ('oximetro', 'Oxímetro'), ('tensiometro', 'Tensiómetro'), ('termometro', 'Termómetro'), ('ecg', 'ECG'), ('otro', 'Otro')], max_length=30)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('bluetooth', 'Bluetooth'), ('wifi', 'WiFi')], max_length=20)),
                ('ble_service_uuid', models.CharField(blank=True, default='', max_length=64)),
                ('ble_characteristic_uuid', models.CharField(blank=True, default='', max_length=64)),
                ('supported_parameters', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device_type', 'name'],
            },
        ),
    ]
