# Generated by Django 5.2.11 on 2026-03-25 20:02

from django.db import migrations


def fix_device_types(apps, schema_editor):
    Device = apps.get_model("devices", "Device")
    Device.objects.filter(device_type="glucometer").update(device_type="glucometro")


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_deviceprofile"),
    ]

    operations = [
        migrations.RunPython(fix_device_types, migrations.RunPython.noop),
    ]
