# Generated by Django 5.2.11 on 2026-03-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_fix_glucometer_to_glucometro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('glucometro', 'Glucómetro'), ('oximetro', 'Oxímetro'), ('tensiometro', 'Tensiómetro'), ('termometro', 'Termómetro'), ('ecg', 'ECG'), ('otro', 'Otro')], max_length=50),
        ),
    ]
