# Generated by Django 5.2.11 on 2026-03-25 20:22

from django.db import migrations

PROFILE_DATA = {
    "name": "Oxímetro de Pulso Yonker YK-67B1",
    "device_type": "oximetro",
    "manufacturer": "Yonker",
    "model_name": "YK-67B1",
    "protocol": "bluetooth",
    "ble_service_uuid": "CDEACD80-5235-4C07-8846-93A37EE6B86D",
    "ble_characteristic_uuid": "CDEACD81-5235-4C07-8846-93A37EE6B86D",
    "supported_parameters": ["spo2", "pulse_rate", "pi_index", "hrv"],
    "is_active": True,
}


def seed_profile(apps, schema_editor):
    DeviceProfile = apps.get_model("devices", "DeviceProfile")
    DeviceProfile.objects.get_or_create(
        model_name=PROFILE_DATA["model_name"],
        defaults=PROFILE_DATA,
    )


def remove_profile(apps, schema_editor):
    DeviceProfile = apps.get_model("devices", "DeviceProfile")
    DeviceProfile.objects.filter(model_name=PROFILE_DATA["model_name"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_device_device_type"),
    ]

    operations = [
        migrations.RunPython(seed_profile, remove_profile),
    ]
