# Generated by Django 5.2.6 on 2026-06-09 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("glucometro", "Glucómetro"),
                            ("oximetro", "Oxímetro"),
                            ("tensiometro", "Tensiómetro"),
                            ("bascula", "Báscula"),
                            ("termometro", "Termómetro"),
                            ("ecg", "ECG"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parameter_type", models.CharField(blank=True, default="", max_length=50)),
                (
                    "rule_kind",
                    models.CharField(
                        choices=[("immediate", "Immediate"), ("weekly", "Weekly")], max_length=20
                    ),
                ),
                (
                    "formula_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold"),
                            ("range_score", "Range score"),
                            ("composite_index", "Composite index"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True, default="")),
                ("summary_template_normal", models.TextField(blank=True, default="")),
                ("summary_template_preventive", models.TextField(blank=True, default="")),
                ("summary_template_critical", models.TextField(blank=True, default="")),
                ("action_template_normal", models.TextField(blank=True, default="")),
                ("action_template_preventive", models.TextField(blank=True, default="")),
                ("action_template_critical", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["device_type", "rule_kind", "parameter_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="recommendation",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("glucometro", "Glucómetro"),
                    ("oximetro", "Oxímetro"),
                    ("tensiometro", "Tensiómetro"),
                    ("bascula", "Báscula"),
                    ("termometro", "Termómetro"),
                    ("ecg", "ECG"),
                    ("otro", "Otro"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="kind",
            field=models.CharField(
                choices=[("immediate", "Immediate"), ("weekly", "Weekly")],
                default="immediate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="metrics_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="rule_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="variables_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="engine",
            field=models.CharField(
                choices=[("rules", "Rules"), ("algorithmic", "Algorithmic")], max_length=20
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendation_outputs",
                to="recommendations.diagnosticrule",
            ),
        ),
        migrations.CreateModel(
            name="DiagnosticRuleVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("label", models.CharField(max_length=120)),
                ("value", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("decimal", "Decimal"),
                            ("integer", "Integer"),
                            ("percentage", "Percentage"),
                        ],
                        default="decimal",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=20)),
                (
                    "min_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "max_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("help_text", models.CharField(blank=True, default="", max_length=255)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="recommendations.diagnosticrule",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "key"],
                "unique_together": {("rule", "key")},
            },
        ),
        migrations.CreateModel(
            name="PeriodicDiagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("glucometro", "Glucómetro"),
                            ("oximetro", "Oxímetro"),
                            ("tensiometro", "Tensiómetro"),
                            ("bascula", "Báscula"),
                            ("termometro", "Termómetro"),
                            ("ecg", "ECG"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly")], default="weekly", max_length=20
                    ),
                ),
                ("rule_version", models.PositiveIntegerField(default=1)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("preventive", "Preventive"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("summary", models.TextField()),
                ("recommended_action", models.TextField(blank=True, default="")),
                ("metrics_snapshot", models.JSONField(blank=True, default=dict)),
                ("variables_snapshot", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodic_diagnostics",
                        to="recommendations.diagnosticrule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_diagnostics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-generated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "device_type", "period_start", "period_end", "frequency"),
                        name="unique_periodic_diagnostic_per_user_device_period",
                    )
                ],
            },
        ),
    ]
