# Generated by Codex on 2026-06-09

from decimal import Decimal

from django.db import migrations


RULES = {
    "glucose-immediate": {
        "name": "Glucosa inmediata",
        "device_type": "glucometro",
        "parameter_type": "glucose",
        "rule_kind": "immediate",
        "formula_type": "threshold",
        "summary": {
            "normal": "Glucosa dentro del rango operativo esperado ({value:.2f} {unit}).",
            "preventive": "Glucosa fuera del rango objetivo ({value:.2f} {unit}). Requiere seguimiento.",
            "critical": "Glucosa en rango crítico ({value:.2f} {unit}). Requiere atención prioritaria.",
        },
        "action": {
            "normal": "Mantener seguimiento habitual.",
            "preventive": "Revisar alimentación, adherencia y repetir medición si es necesario.",
            "critical": "Buscar atención médica si el valor persiste o hay síntomas.",
        },
        "variables": [
            ("low_critical", "Hipoglucemia crítica", "54", "integer", "mg/dL", "20", "100"),
            ("low_alert", "Hipoglucemia", "70", "integer", "mg/dL", "40", "120"),
            ("high_alert", "Hiperglucemia", "180", "integer", "mg/dL", "100", "300"),
            ("high_critical", "Hiperglucemia crítica", "250", "integer", "mg/dL", "140", "500"),
            ("weekly_high_pct", "% semanal alto", "0.20", "percentage", "", "0", "1"),
            ("weekly_avg_alert", "Promedio semanal alerta", "140", "integer", "mg/dL", "80", "250"),
            ("min_readings_week", "Mínimo lecturas semana", "4", "integer", "", "1", "50"),
        ],
    },
    "glucose-weekly": {
        "name": "Glucosa semanal",
        "device_type": "glucometro",
        "parameter_type": "",
        "rule_kind": "weekly",
        "formula_type": "range_score",
        "summary": {
            "normal": "Resumen semanal de glucosa estable. Promedio {avg_glucose:.2f} {unit}.",
            "preventive": "Resumen semanal de glucosa con excursiones fuera de rango. Promedio {avg_glucose:.2f} {unit}.",
            "critical": "Resumen semanal de glucosa con eventos críticos detectados. Promedio {avg_glucose:.2f} {unit}.",
        },
        "action": {
            "normal": "Mantener monitoreo y hábitos actuales.",
            "preventive": "Revisar patrones de alimentación y control según indicación clínica.",
            "critical": "Priorizar revisión clínica y confirmar lecturas recientes.",
        },
        "variables": [
            ("low_critical", "Hipoglucemia crítica", "54", "integer", "mg/dL", "20", "100"),
            ("low_alert", "Hipoglucemia", "70", "integer", "mg/dL", "40", "120"),
            ("high_alert", "Hiperglucemia", "180", "integer", "mg/dL", "100", "300"),
            ("high_critical", "Hiperglucemia crítica", "250", "integer", "mg/dL", "140", "500"),
            ("weekly_high_pct", "% semanal alto", "0.20", "percentage", "", "0", "1"),
            ("weekly_avg_alert", "Promedio semanal alerta", "140", "integer", "mg/dL", "80", "250"),
            ("min_readings_week", "Mínimo lecturas semana", "4", "integer", "", "1", "50"),
        ],
    },
    "spo2-immediate": {
        "name": "Oximetría inmediata SpO2",
        "device_type": "oximetro",
        "parameter_type": "spo2",
        "rule_kind": "immediate",
        "formula_type": "threshold",
        "summary": {
            "normal": "Saturación de oxígeno en rango esperado ({value:.2f} {unit}).",
            "preventive": "Saturación de oxígeno por debajo del rango óptimo ({value:.2f} {unit}).",
            "critical": "Saturación de oxígeno críticamente baja ({value:.2f} {unit}).",
        },
        "action": {
            "normal": "Mantener seguimiento habitual.",
            "preventive": "Repetir medición en reposo y vigilar síntomas.",
            "critical": "Buscar atención clínica urgente si el valor persiste.",
        },
        "variables": [
            ("spo2_normal_min", "SpO2 mínima normal", "95", "integer", "%", "80", "100"),
            ("spo2_warning_min", "SpO2 advertencia", "93", "integer", "%", "70", "100"),
            ("spo2_critical_max", "SpO2 crítica", "92", "integer", "%", "70", "100"),
            ("spo2_emergency_max", "SpO2 emergencia", "89", "integer", "%", "70", "100"),
            ("pulse_normal_min", "Pulso normal mínimo", "60", "integer", "bpm", "20", "120"),
            ("pulse_normal_max", "Pulso normal máximo", "100", "integer", "bpm", "40", "150"),
            ("pulse_critical_low", "Pulso crítico bajo", "50", "integer", "bpm", "20", "80"),
            ("pulse_critical_high", "Pulso crítico alto", "120", "integer", "bpm", "80", "220"),
            ("weekly_low_spo2_count", "Conteo SpO2 baja", "2", "integer", "", "1", "20"),
            ("weekly_high_pulse_pct", "% pulso alto", "0.20", "percentage", "", "0", "1"),
            ("min_readings_week", "Mínimo lecturas semana", "4", "integer", "", "1", "50"),
        ],
    },
    "pulse-immediate": {
        "name": "Oximetría inmediata pulso",
        "device_type": "oximetro",
        "parameter_type": "pulse_rate",
        "rule_kind": "immediate",
        "formula_type": "threshold",
        "summary": {
            "normal": "Frecuencia de pulso dentro del rango esperado ({value:.2f} {unit}).",
            "preventive": "Frecuencia de pulso fuera del rango habitual ({value:.2f} {unit}).",
            "critical": "Frecuencia de pulso en rango crítico ({value:.2f} {unit}).",
        },
        "action": {
            "normal": "Mantener seguimiento habitual.",
            "preventive": "Repetir medición en reposo y vigilar síntomas.",
            "critical": "Buscar atención médica si el valor persiste o hay síntomas.",
        },
        "variables": [
            ("pulse_normal_min", "Pulso normal mínimo", "60", "integer", "bpm", "20", "120"),
            ("pulse_normal_max", "Pulso normal máximo", "100", "integer", "bpm", "40", "150"),
            ("pulse_critical_low", "Pulso crítico bajo", "50", "integer", "bpm", "20", "80"),
            ("pulse_critical_high", "Pulso crítico alto", "120", "integer", "bpm", "80", "220"),
            ("min_readings_week", "Mínimo lecturas semana", "4", "integer", "", "1", "50"),
        ],
    },
    "oximetry-weekly": {
        "name": "Oximetría semanal",
        "device_type": "oximetro",
        "parameter_type": "",
        "rule_kind": "weekly",
        "formula_type": "composite_index",
        "summary": {
            "normal": "Resumen semanal de oximetría estable. Promedio SpO2 {avg_spo2:.2f} {spo2_unit}.",
            "preventive": "Resumen semanal de oximetría con valores bajos o pulso alterado. Promedio SpO2 {avg_spo2:.2f} {spo2_unit}.",
            "critical": "Resumen semanal de oximetría con eventos críticos detectados. Promedio SpO2 {avg_spo2:.2f} {spo2_unit}.",
        },
        "action": {
            "normal": "Mantener monitoreo habitual.",
            "preventive": "Repetir mediciones en reposo y revisar tendencia.",
            "critical": "Buscar valoración clínica si persisten lecturas bajas o síntomas.",
        },
        "variables": [
            ("spo2_normal_min", "SpO2 mínima normal", "95", "integer", "%", "80", "100"),
            ("spo2_warning_min", "SpO2 advertencia", "93", "integer", "%", "70", "100"),
            ("spo2_critical_max", "SpO2 crítica", "92", "integer", "%", "70", "100"),
            ("spo2_emergency_max", "SpO2 emergencia", "89", "integer", "%", "70", "100"),
            ("pulse_normal_min", "Pulso normal mínimo", "60", "integer", "bpm", "20", "120"),
            ("pulse_normal_max", "Pulso normal máximo", "100", "integer", "bpm", "40", "150"),
            ("pulse_critical_low", "Pulso crítico bajo", "50", "integer", "bpm", "20", "80"),
            ("pulse_critical_high", "Pulso crítico alto", "120", "integer", "bpm", "80", "220"),
            ("weekly_low_spo2_count", "Conteo SpO2 baja", "2", "integer", "", "1", "20"),
            ("weekly_high_pulse_pct", "% pulso alto", "0.20", "percentage", "", "0", "1"),
            ("min_readings_week", "Mínimo lecturas semana", "4", "integer", "", "1", "50"),
        ],
    },
    "bp-systolic-immediate": {
        "name": "Tensión inmediata sistólica",
        "device_type": "tensiometro",
        "parameter_type": "bp_systolic",
        "rule_kind": "immediate",
        "formula_type": "threshold",
        "summary": {
            "normal": "Presión sistólica en rango esperado ({value:.2f} {unit}).",
            "preventive": "Presión sistólica elevada ({value:.2f} {unit}).",
            "critical": "Presión sistólica críticamente elevada ({value:.2f} {unit}).",
        },
        "action": {
            "normal": "Mantener seguimiento habitual.",
            "preventive": "Repetir medición en reposo y vigilar tendencia.",
            "critical": "Buscar valoración médica prioritaria si persiste.",
        },
        "variables": [
            ("sys_normal_max", "Sistólica normal máxima", "119", "integer", "mmHg", "80", "160"),
            ("sys_elevated_min", "Sistólica elevada", "120", "integer", "mmHg", "80", "180"),
            ("sys_stage1_min", "Sistólica etapa 1", "130", "integer", "mmHg", "90", "220"),
            ("sys_stage2_min", "Sistólica etapa 2", "140", "integer", "mmHg", "100", "240"),
            ("sys_urgent_min", "Sistólica urgencia", "180", "integer", "mmHg", "120", "260"),
            ("dia_normal_max", "Diastólica normal máxima", "79", "integer", "mmHg", "40", "120"),
            ("dia_stage1_min", "Diastólica etapa 1", "80", "integer", "mmHg", "40", "140"),
            ("dia_stage2_min", "Diastólica etapa 2", "90", "integer", "mmHg", "50", "160"),
            ("dia_urgent_min", "Diastólica urgencia", "120", "integer", "mmHg", "60", "180"),
            ("weekly_required_days", "Días requeridos", "2", "integer", "", "1", "7"),
            ("min_readings_week", "Mínimo lecturas semana", "4", "integer", "", "1", "50"),
        ],
    },
    "bp-diastolic-immediate": {
        "name": "Tensión inmediata diastólica",
        "device_type": "tensiometro",
        "parameter_type": "bp_diastolic",
        "rule_kind": "immediate",
        "formula_type": "threshold",
        "summary": {
            "normal": "Presión diastólica en rango esperado ({value:.2f} {unit}).",
            "preventive": "Presión diastólica elevada ({value:.2f} {unit}).",
            "critical": "Presión diastólica críticamente elevada ({value:.2f} {unit}).",
        },
        "action": {
            "normal": "Mantener seguimiento habitual.",
            "preventive": "Repetir medición en reposo y vigilar tendencia.",
            "critical": "Buscar valoración médica prioritaria si persiste.",
        },
        "variables": [
            ("sys_normal_max", "Sistólica normal máxima", "119", "integer", "mmHg", "80", "160"),
            ("sys_elevated_min", "Sistólica elevada", "120", "integer", "mmHg", "80", "180"),
            ("sys_stage1_min", "Sistólica etapa 1", "130", "integer", "mmHg", "90", "220"),
            ("sys_stage2_min", "Sistólica etapa 2", "140", "integer", "mmHg", "100", "240"),
            ("sys_urgent_min", "Sistólica urgencia", "180", "integer", "mmHg", "120", "260"),
            ("dia_normal_max", "Diastólica normal máxima", "79", "integer", "mmHg", "40", "120"),
            ("dia_stage1_min", "Diastólica etapa 1", "80", "integer", "mmHg", "40", "140"),
            ("dia_stage2_min", "Diastólica etapa 2", "90", "integer", "mmHg", "50", "160"),
            ("dia_urgent_min", "Diastólica urgencia", "120", "integer", "mmHg", "60", "180"),
            ("weekly_required_days", "Días requeridos", "2", "integer", "", "1", "7"),
            ("min_readings_week", "Mínimo lecturas semana", "4", "integer", "", "1", "50"),
        ],
    },
    "blood-pressure-weekly": {
        "name": "Tensión semanal",
        "device_type": "tensiometro",
        "parameter_type": "",
        "rule_kind": "weekly",
        "formula_type": "composite_index",
        "summary": {
            "normal": "Resumen semanal de presión arterial estable. Promedio {avg_systolic:.2f}/{avg_diastolic:.2f} mmHg.",
            "preventive": "Resumen semanal de presión arterial con tendencia elevada. Promedio {avg_systolic:.2f}/{avg_diastolic:.2f} mmHg.",
            "critical": "Resumen semanal de presión arterial con eventos críticos detectados. Promedio {avg_systolic:.2f}/{avg_diastolic:.2f} mmHg.",
        },
        "action": {
            "normal": "Mantener monitoreo habitual.",
            "preventive": "Revisar mediciones en reposo y seguir control clínico.",
            "critical": "Buscar valoración clínica prioritaria si la elevación persiste.",
        },
        "variables": [
            ("sys_normal_max", "Sistólica normal máxima", "119", "integer", "mmHg", "80", "160"),
            ("sys_elevated_min", "Sistólica elevada", "120", "integer", "mmHg", "80", "180"),
            ("sys_stage1_min", "Sistólica etapa 1", "130", "integer", "mmHg", "90", "220"),
            ("sys_stage2_min", "Sistólica etapa 2", "140", "integer", "mmHg", "100", "240"),
            ("sys_urgent_min", "Sistólica urgencia", "180", "integer", "mmHg", "120", "260"),
            ("dia_normal_max", "Diastólica normal máxima", "79", "integer", "mmHg", "40", "120"),
            ("dia_stage1_min", "Diastólica etapa 1", "80", "integer", "mmHg", "40", "140"),
            ("dia_stage2_min", "Diastólica etapa 2", "90", "integer", "mmHg", "50", "160"),
            ("dia_urgent_min", "Diastólica urgencia", "120", "integer", "mmHg", "60", "180"),
            ("weekly_required_days", "Días requeridos", "2", "integer", "", "1", "7"),
            ("min_readings_week", "Mínimo lecturas semana", "4", "integer", "", "1", "50"),
        ],
    },
}


def seed_rules(apps, schema_editor):
    DiagnosticRule = apps.get_model("recommendations", "DiagnosticRule")
    DiagnosticRuleVariable = apps.get_model("recommendations", "DiagnosticRuleVariable")
    Recommendation = apps.get_model("recommendations", "Recommendation")

    for slug, config in RULES.items():
        rule, _ = DiagnosticRule.objects.update_or_create(
            slug=slug,
            defaults={
                "name": config["name"],
                "device_type": config["device_type"],
                "parameter_type": config["parameter_type"],
                "rule_kind": config["rule_kind"],
                "formula_type": config["formula_type"],
                "is_active": True,
                "version": 1,
                "summary_template_normal": config["summary"]["normal"],
                "summary_template_preventive": config["summary"]["preventive"],
                "summary_template_critical": config["summary"]["critical"],
                "action_template_normal": config["action"]["normal"],
                "action_template_preventive": config["action"]["preventive"],
                "action_template_critical": config["action"]["critical"],
            },
        )
        for index, (key, label, value, value_type, unit, min_value, max_value) in enumerate(
            config["variables"]
        ):
            DiagnosticRuleVariable.objects.update_or_create(
                rule=rule,
                key=key,
                defaults={
                    "label": label,
                    "value": Decimal(value),
                    "value_type": value_type,
                    "unit": unit,
                    "min_value": Decimal(min_value),
                    "max_value": Decimal(max_value),
                    "sort_order": index,
                },
            )

    for recommendation in Recommendation.objects.select_related("measurement", "measurement__device"):
        if recommendation.measurement_id and recommendation.measurement and recommendation.measurement.device_id:
            recommendation.device_type = recommendation.measurement.device.device_type
        recommendation.kind = "immediate"
        if recommendation.engine == "ai":
            recommendation.engine = "algorithmic"
        recommendation.save(update_fields=["device_type", "kind", "engine"])


def unseed_rules(apps, schema_editor):
    DiagnosticRule = apps.get_model("recommendations", "DiagnosticRule")
    DiagnosticRule.objects.filter(slug__in=RULES.keys()).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0002_diagnosticrule_recommendation_device_type_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_rules, unseed_rules),
    ]
